services:
  backend:
    build: .
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             uvicorn index.asgi:application --host 0.0.0.0 --port 8000"